Python 3 base image with PrivX SDK 26.0 libraries
demisto/dockerfiles pull request #13330
Opened 2023-03-21 17:10 UTC by jjh-ssh

## Status
Ready

## Related Content Pull Request
@kgal-pan 

## Related Issues

## Description
Python 3 base image including Python libraries for PrivX SDK 26.0. Used by incoming PrivX integration.

PrivX Python SDK:
https://github.com/SSHcom/privx-sdk-for-python

PrivX documentation:
https://privx.docs.ssh.com

2023-03-21 17:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/dockerfiles?pullRequest=13330) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/dockerfiles?pullRequest=13330) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/dockerfiles?pullRequest=13330) it.</sub>

2023-03-21 17:14 UTC, jjh-ssh commented
Re-created the original PR with cleaned up commit history + rebased to master.

2023-03-27 07:03 UTC, glicht requested changes

2023-03-27 11:00 UTC, jjh-ssh commented on docker/privx-api/Dockerfile
> +  && pip install git+https://github.com/SSHcom/privx-sdk-for-python.git@v26.0.0#egg=privx_api \
Moved privx-api installation to Pipfile as suggested.

2023-03-29 06:53 UTC, JudahSchwartz commented
@glicht looking into it. Added the approve label to allow merging in the meanwhile

2023-05-01 09:51 UTC, merged