add websockets to python docker files
demisto/dockerfiles pull request #19064
Opened 2023-08-10 12:22 UTC by ilaner

## Status
Ready/In Progress/In Hold (Reason for hold)

## Related Content Pull Request
Related PR: link to the PR at demisto/content

## Related Issues
Related: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

2023-08-13 07:15 UTC, JudahSchwartz requested changes
as discussed, this should be its own docker

2023-08-13 08:53 UTC, JudahSchwartz reviewed
verify script please
Is this for a specific content item or dev only?
can we add devonly to the conf?

2023-08-13 10:06 UTC, ilaner commented
> verify script please
Is this for a specific content item or dev only?
can we add devonly to the conf? 

This is used for content items that work with websockets instead of REST api.
Added verify script

2023-08-16 15:40 UTC, JudahSchwartz approved these changes

2023-08-17 07:46 UTC, merged