rename the port.txt file to chrome_instances.tsv in the docker image
demisto/dockerfiles pull request #27235
Opened 2024-05-28 12:06 UTC by ilaredo

## Status
Ready

## Related Issues
[Jira ticket](https://jira-dc.paloaltonetworks.com/browse/CIAC-10544)

## Description
I had to change the port.txt file to tsv file

2024-05-28 12:55 UTC, tkatzir approved these changes
Great! Approved.
Make sure you merge it right before you merge the PR in Content.

2024-07-01 08:11 UTC, dorschw commented on docker/py3-native/pyproject.toml
> -PyPDF2 = "*"
intended?

2024-07-01 08:18 UTC, dorschw requested changes
https://panw-global.slack.com/archives/C07AJNKPFL4/p1719821448816529

2024-07-01 08:31 UTC, dorschw approved these changes

2024-07-01 12:35 UTC, merged