Build ML docker
demisto/dockerfiles pull request #2845
Opened 2020-10-05 15:45 UTC by yguezpa

## Status
Ready/In Progress/In Hold (Reason for hold)
In Progress

## Related Issues
related: Create demisto ML python3 docker as part of dockerfile repo #28938

## Description
Create a new docker for ML tasks that we contains packages needed for Phishing (for now) and will be updated in the future with more packages

2020-10-05 19:00 UTC, glicht requested changes

2020-10-05 19:00 UTC, glicht commented on docker/ml/Pipfile
> +[packages]
all python packages should be defined here

2020-10-05 19:00 UTC, glicht commented on docker/ml/Dockerfile
> +RUN pip3 install spacy
you should not install packages via pip3 in the Dockerfile. This is done via the use of the Pipfile and Pipfile.lock.

2020-10-06 15:50 UTC, closed without merging

2020-10-06 15:51 UTC, yguezpa commented
create a new PR