Added packer image for AMI builds
demisto/dockerfiles pull request #3046
Opened 2020-10-28 10:41 UTC by hod-alpert

## Status
Ready

## Related Issues
related: https://github.com/demisto/etc/issues/25490

## Description
Created am image with packer and it's dependencies

2020-10-28 11:54 UTC, glicht commented
Is this only for development?

2020-10-28 12:18 UTC, dc-builder commented
# Docker Image Ready - Dev

Docker automatic build at CircleCI has deployed your docker image: devdemisto/packer:1.0.0.12921
It is available now on docker hub at: https://hub.docker.com/r/devdemisto/packer/tags
Get started by pulling the image:
```
docker pull devdemisto/packer:1.0.0.12921
```

## Docker Metadata
- Image Size: `387.30 MB`

- Image ID: `sha256:6a5f2ea364ed907467015145da59c1b1b2c6823d16f0b475a3e140b3c2bf009f`
- Created: `2020-10-28T12:17:31.350141875Z`
- Arch: `linux`/`amd64`
- Command: `["python3"]`
- Environment:
  - `PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG=C.UTF-8`
  - `GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568`
  - `PYTHON_VERSION=3.8.6`
  - `PYTHON_PIP_VERSION=20.2.3`
  - `PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/fa7dc83944936bf09a0e4cb5d5ec852c0d256599/get-pip.py`
  - `PYTHON_GET_PIP_SHA256=6e0bb0a2c2533361d7f297ed547237caf1b7507f197835974c0dd7eba998c53c`
  - `DOCKER_IMAGE=devdemisto/packer:1.0.0.12921`
- Labels:
  - `org.opencontainers.image.authors:Demisto <containers@demisto.com>`
  - `org.opencontainers.image.revision:36617a3792a538a3368d9274b8e15dcd3f377b0c`
  - `org.opencontainers.image.version:1.0.0.12921`

2020-10-28 12:24 UTC, hod-alpert commented
> Is this only for development?

@glicht Yes

2020-10-28 14:07 UTC, dc-builder commented
# Docker Image Ready - Dev

Docker automatic build at CircleCI has deployed your docker image: devdemisto/packer:1.0.0.12922
It is available now on docker hub at: https://hub.docker.com/r/devdemisto/packer/tags
Get started by pulling the image:
```
docker pull devdemisto/packer:1.0.0.12922
```

## Docker Metadata
- Image Size: `387.31 MB`

- Image ID: `sha256:ce60e0aaf4eff5d2d38d7a670665131106bdc206146e61b12cc0975612842602`
- Created: `2020-10-28T14:05:58.609932735Z`
- Arch: `linux`/`amd64`
- Command: `["python3"]`
- Environment:
  - `PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG=C.UTF-8`
  - `GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568`
  - `PYTHON_VERSION=3.8.6`
  - `PYTHON_PIP_VERSION=20.2.3`
  - `PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/fa7dc83944936bf09a0e4cb5d5ec852c0d256599/get-pip.py`
  - `PYTHON_GET_PIP_SHA256=6e0bb0a2c2533361d7f297ed547237caf1b7507f197835974c0dd7eba998c53c`
  - `DOCKER_IMAGE=devdemisto/packer:1.0.0.12922`
- Labels:
  - `org.opencontainers.image.authors:Demisto <containers@demisto.com>`
  - `org.opencontainers.image.revision:9d832de6aa9ce6271a548bb49ed3f10d3a58aed1`
  - `org.opencontainers.image.version:1.0.0.12922`

2020-10-29 09:32 UTC, glicht requested changes
If this is for dev only add to build.conf: `devonly=true`. Remove the license changes as this is dev only. Also please use Pipfile for installing python dependencies as we do in the other images.

2020-10-29 11:12 UTC, dc-builder commented
# Docker Image Ready - Dev

Docker automatic build at CircleCI has deployed your docker image: devdemisto/packer:1.0.0.12945
It is available now on docker hub at: https://hub.docker.com/r/devdemisto/packer/tags
Get started by pulling the image:
```
docker pull devdemisto/packer:1.0.0.12945
```

## Docker Metadata
- Image Size: `387.31 MB`

- Image ID: `sha256:1f7c008309706d0d3d2a5631ebc09bfcfdef1dd706ad4d406e993a853c2b96ac`
- Created: `2020-10-29T11:11:08.976769236Z`
- Arch: `linux`/`amd64`
- Command: `["python3"]`
- Environment:
  - `PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG=C.UTF-8`
  - `GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568`
  - `PYTHON_VERSION=3.8.6`
  - `PYTHON_PIP_VERSION=20.2.3`
  - `PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/fa7dc83944936bf09a0e4cb5d5ec852c0d256599/get-pip.py`
  - `PYTHON_GET_PIP_SHA256=6e0bb0a2c2533361d7f297ed547237caf1b7507f197835974c0dd7eba998c53c`
  - `DOCKER_IMAGE=devdemisto/packer:1.0.0.12945`
- Labels:
  - `org.opencontainers.image.authors:Demisto <containers@demisto.com>`
  - `org.opencontainers.image.revision:731e691c6a6ac7c67cc87f1eb660e9b918637392`
  - `org.opencontainers.image.version:1.0.0.12945`

2020-10-29 13:51 UTC, glicht commented on docker/packer/Dockerfile
> +RUN pip3 install jinja2 requests python-dateutil dateparser pyyaml ansible jmespath
please change to use a Pipfile and Pipfile.lock as we do with other images.

2020-10-29 13:51 UTC, glicht commented on docker/packer/Dockerfile
> +RUN curl -so packer.zip $(curl -sk https://www.packer.io/downloads.html |grep -oE https://releases\.hashicorp\.com/packer/\[0-9.\]\{5\}/packer_\[0-9.\]\{5\}_linux_amd64\.zip)
Please use a specific version which is locked.

2020-10-29 13:53 UTC, glicht commented on docker/packer/Dockerfile
> +RUN curl -so packer.zip $(curl -sk https://www.packer.io/downloads.html |grep -oE https://releases\.hashicorp\.com/packer/\[0-9.\]\{5\}/packer_\[0-9.\]\{5\}_linux_amd64\.zip)
Or if you want the latest include a printout of the version when done installing as we do with gcloud install.

2020-10-29 17:51 UTC, dc-builder commented
# Docker Image Ready - Dev

Docker automatic build at CircleCI has deployed your docker image: devdemisto/packer:1.0.0.13007
It is available now on docker hub at: https://hub.docker.com/r/devdemisto/packer/tags
Get started by pulling the image:
```
docker pull devdemisto/packer:1.0.0.13007
```

## Docker Metadata
- Image Size: `316.58 MB`

- Image ID: `sha256:9a0147881d199fef5dad11097f7c1615c8d1f698ff18d6024e8c1c548a0eb776`
- Created: `2020-10-29T17:50:34.630550426Z`
- Arch: `linux`/`amd64`
- Command: `["python3"]`
- Environment:
  - `PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG=C.UTF-8`
  - `GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568`
  - `PYTHON_VERSION=3.8.6`
  - `PYTHON_PIP_VERSION=20.2.3`
  - `PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/fa7dc83944936bf09a0e4cb5d5ec852c0d256599/get-pip.py`
  - `PYTHON_GET_PIP_SHA256=6e0bb0a2c2533361d7f297ed547237caf1b7507f197835974c0dd7eba998c53c`
  - `DOCKER_IMAGE=devdemisto/packer:1.0.0.13007`
- Labels:
  - `org.opencontainers.image.authors:Demisto <containers@demisto.com>`
  - `org.opencontainers.image.revision:7591a9715b3a0ec8549d7420001c17dc69e51c7e`
  - `org.opencontainers.image.version:1.0.0.13007`

2020-10-30 05:10 UTC, dc-builder commented
# Docker Image Ready - Dev

Docker automatic build at CircleCI has deployed your docker image: devdemisto/packer:1.0.0.13025
It is available now on docker hub at: https://hub.docker.com/r/devdemisto/packer/tags
Get started by pulling the image:
```
docker pull devdemisto/packer:1.0.0.13025
```

## Docker Metadata
- Image Size: `317.92 MB`

- Image ID: `sha256:b3d84e615216f625472e5183a7b0a745ff25fee1912fecf33703ba909d73949b`
- Created: `2020-10-30T05:09:18.250022643Z`
- Arch: `linux`/`amd64`
- Command: `["python3"]`
- Environment:
  - `PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG=C.UTF-8`
  - `GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568`
  - `PYTHON_VERSION=3.8.6`
  - `PYTHON_PIP_VERSION=20.2.3`
  - `PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/fa7dc83944936bf09a0e4cb5d5ec852c0d256599/get-pip.py`
  - `PYTHON_GET_PIP_SHA256=6e0bb0a2c2533361d7f297ed547237caf1b7507f197835974c0dd7eba998c53c`
  - `DOCKER_IMAGE=devdemisto/packer:1.0.0.13025`
- Labels:
  - `org.opencontainers.image.authors:Demisto <containers@demisto.com>`
  - `org.opencontainers.image.revision:53df1070343fac4df20552d800d9e3cefe622087`
  - `org.opencontainers.image.version:1.0.0.13025`

2020-10-30 07:59 UTC, dc-builder commented
# Docker Image Ready - Dev

Docker automatic build at CircleCI has deployed your docker image: devdemisto/packer:1.0.0.13055
It is available now on docker hub at: https://hub.docker.com/r/devdemisto/packer/tags
Get started by pulling the image:
```
docker pull devdemisto/packer:1.0.0.13055
```

## Docker Metadata
- Image Size: `317.92 MB`

- Image ID: `sha256:a67346ad82d7a3c3df0e76601e1f6a4dea4884ee57e0fa73fd85682f5e9a063e`
- Created: `2020-10-30T07:58:06.423936983Z`
- Arch: `linux`/`amd64`
- Command: `["python3"]`
- Environment:
  - `PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG=C.UTF-8`
  - `GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568`
  - `PYTHON_VERSION=3.8.6`
  - `PYTHON_PIP_VERSION=20.2.3`
  - `PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/fa7dc83944936bf09a0e4cb5d5ec852c0d256599/get-pip.py`
  - `PYTHON_GET_PIP_SHA256=6e0bb0a2c2533361d7f297ed547237caf1b7507f197835974c0dd7eba998c53c`
  - `DOCKER_IMAGE=devdemisto/packer:1.0.0.13055`
- Labels:
  - `org.opencontainers.image.authors:Demisto <containers@demisto.com>`
  - `org.opencontainers.image.revision:639f837b5b4f0cf4c41ac629da9439d29b56c494`
  - `org.opencontainers.image.version:1.0.0.13055`

2020-10-30 12:27 UTC, glicht approved these changes

2020-10-30 14:09 UTC, merged