Gitlab ci base
demisto/dockerfiles pull request #3301
Opened 2020-12-03 11:25 UTC by agamm

## Status
Ready

## Related Issues
Will be used for CI.

## Description
Instead of: https://github.com/demisto/dockerfiles/pull/2500

2020-12-03 14:48 UTC, glicht requested changes

2020-12-03 14:48 UTC, glicht commented on docker/gitlab-ci/build.conf
> +secondly=true
Change to devonly=true

2020-12-27 17:12 UTC, agamm commented on docker/gitlab-ci/build.conf
> +secondly=true
Good now?

2020-12-27 17:20 UTC, glicht approved these changes

2020-12-27 17:25 UTC, dc-builder commented
# Docker Image Ready - Dev

Docker automatic build at CircleCI has deployed your docker image: devdemisto/gitlab-ci:1.0.0.14904
It is available now on docker hub at: https://hub.docker.com/r/devdemisto/gitlab-ci/tags
Get started by pulling the image:
```
docker pull devdemisto/gitlab-ci:1.0.0.14904
```

## Docker Metadata
- Image Size: `931.45 MB`

- Image ID: `sha256:0510b6be6bcd0a523ae9fb2e8f6327090a19596128be895e5a1ed6da9e35c0e6`
- Created: `2020-12-27T17:22:40.803131857Z`
- Arch: `linux`/`amd64`
- Command: `["/bin/sh","-c","/bin/bash"]`
- Environment:
  - `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `DOCKER_IMAGE=devdemisto/gitlab-ci:1.0.0.14904`
- Labels:
  - `org.opencontainers.image.authors:Demisto <containers@demisto.com>`
  - `org.opencontainers.image.revision:8c1ee4e6a163287d877c04e75bc03f89d6bb6463`
  - `org.opencontainers.image.version:1.0.0.14904`

2020-12-28 11:40 UTC, merged