Auto update dockerfiles
demisto/dockerfiles pull request #7322
Opened 2022-03-29 07:27 UTC by iyeshaya

## Status
Ready

## Related Issues
https://github.com/demisto/etc/issues/40874

## Description
Added few Github actions to auto update the dockerfiles in this repo

2022-04-02 20:51 UTC, ShahafBenYakir requested changes
Great work!

2022-04-02 20:51 UTC, ShahafBenYakir commented on utils/auto_dockerfile_update/update_dockerfiles.py
> +                original_branch.checkout()
let's extract this logic into another function, we could then call it from both update_internal_base_dockerfile and update_external_base_dockerfiles

2022-04-11 14:00 UTC, iyeshaya commented on utils/auto_dockerfile_update/get_dockerfiles.py
> +    dockerfiles_paths = glob(f"{base_path}/**/Dockerfile")
Currently we don't have Dockerfiles nested in sub-dirs, but I will add the change to prevent issues in the future.

2022-04-11 14:46 UTC, iyeshaya commented on utils/auto_dockerfile_update/get_latest_tag.py
> +def parse_versions(full_image_name: Union[str, Dict], key='name') -> List[Tuple[int, int, int]]:
When we have tag like: `alpine-3.14-python-3.10.1` those libraries doesn't work as we would like to.

2022-04-11 14:46 UTC, iyeshaya commented on utils/auto_dockerfile_update/update_dockerfiles.py
> +            # if the latest tag update date is newer than the dockerfile
We are using images without the micro/patch versioning (for example `alpine-3.14`), when a new version like `3.14.X` is created they also update the "parent" image.

2022-04-11 14:46 UTC, iyeshaya commented on utils/auto_dockerfile_update/get_latest_tag.py
> +        the latest tag element
For powershell images we get str list and for the other images we get list of dictionary with useful data.

2022-04-11 14:57 UTC, iyeshaya commented on utils/auto_dockerfile_update/get_dockerfiles.py
> +                     internal=False) -> List[Dict]:
But what if someone needs to extract all the dockerfiles in the repo or only the internal devonly files?

2022-04-11 19:41 UTC, ShahafBenYakir commented on utils/auto_dockerfile_update/get_dockerfiles.py
> +                     internal=False) -> List[Dict]:
Do we think such scenario is realistic?

2022-04-12 11:37 UTC, iyeshaya commented on utils/auto_dockerfile_update/get_dockerfiles.py
> +                     internal=False) -> List[Dict]:
Yes, I did some of those queries myself while developing this script.

2022-04-18 10:02 UTC, iyeshaya commented on utils/auto_dockerfile_update/update_dockerfiles.py
> +            # if the latest tag update date is newer than the dockerfile
They update the image, we can monitor this using the update date.

2022-04-19 08:23 UTC, ShahafBenYakir approved these changes

2022-04-19 08:36 UTC, merged