create docker image google-api-python3
demisto/dockerfiles pull request #9365
Opened 2022-10-30 10:34 UTC by sapirshuker

## Status
Ready/**In Progress**/In Hold (Reason for hold)

## Related Content Pull Request
Related PR: -

## Related Issues
Related: https://github.com/demisto/etc/issues/20992

## Description
create a new docker image in order to replace deprecated package.

2022-10-30 12:08 UTC, dc-builder commented
# Docker Image Ready - Dev

Docker automatic build at CircleCI has deployed your docker image: devdemisto/google-api-python3:1.0.0.36843
It is available now on docker hub at: https://hub.docker.com/r/devdemisto/google-api-python3/tags
Get started by pulling the image:
```
docker pull devdemisto/google-api-python3:1.0.0.36843
```

## Docker Metadata
- Image Size: `44.58 MB`

- Image ID: `sha256:6921b827cc94edca13a30d7f29c5ec1b29dd46b83345328cc85f5e48cdb02b8c`
- Created: `2022-10-30T12:08:22.206894097Z`
- Arch: `linux`/`amd64`
- Command: `["python3"]`
- Environment:
  - `PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG=C.UTF-8`
  - `GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D`
  - `PYTHON_VERSION=3.10.8`
  - `PYTHON_PIP_VERSION=22.2.2`
  - `PYTHON_SETUPTOOLS_VERSION=63.2.0`
  - `PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/5eaac1050023df1f5c98b173b248c260023f2278/public/get-pip.py`
  - `PYTHON_GET_PIP_SHA256=5aefe6ade911d997af080b315ebcb7f882212d070465df544e1175ac2be519b4`
  - `DOCKER_IMAGE=devdemisto/google-api-python3:1.0.0.36843`
- Labels:
  - `org.opencontainers.image.authors:Demisto <containers@demisto.com>`
  - `org.opencontainers.image.revision:dc5299e9d4c408aef783ef5e440516e4174a08d9`
  - `org.opencontainers.image.version:1.0.0.36843`

2022-10-30 13:25 UTC, dc-builder commented
# Docker Image Ready - Dev

Docker automatic build at CircleCI has deployed your docker image: devdemisto/google-api-python3:1.0.0.36844
It is available now on docker hub at: https://hub.docker.com/r/devdemisto/google-api-python3/tags
Get started by pulling the image:
```
docker pull devdemisto/google-api-python3:1.0.0.36844
```

## Docker Metadata
- Image Size: `44.58 MB`

- Image ID: `sha256:66e6864dbb582c378e9428f778ffb4f835710f4db6d7e84c3215f04cf3ba713c`
- Created: `2022-10-30T13:25:17.960036151Z`
- Arch: `linux`/`amd64`
- Command: `["python3"]`
- Environment:
  - `PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG=C.UTF-8`
  - `GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D`
  - `PYTHON_VERSION=3.10.8`
  - `PYTHON_PIP_VERSION=22.2.2`
  - `PYTHON_SETUPTOOLS_VERSION=63.2.0`
  - `PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/5eaac1050023df1f5c98b173b248c260023f2278/public/get-pip.py`
  - `PYTHON_GET_PIP_SHA256=5aefe6ade911d997af080b315ebcb7f882212d070465df544e1175ac2be519b4`
  - `DOCKER_IMAGE=devdemisto/google-api-python3:1.0.0.36844`
- Labels:
  - `org.opencontainers.image.authors:Demisto <containers@demisto.com>`
  - `org.opencontainers.image.revision:28c0672fa20198a813c054e1b9224bd75afd8731`
  - `org.opencontainers.image.version:1.0.0.36844`

2022-10-30 15:06 UTC, dc-builder commented
# Docker Image Ready - Dev

Docker automatic build at CircleCI has deployed your docker image: devdemisto/google-api-python3:1.0.0.36882
It is available now on docker hub at: https://hub.docker.com/r/devdemisto/google-api-python3/tags
Get started by pulling the image:
```
docker pull devdemisto/google-api-python3:1.0.0.36882
```

## Docker Metadata
- Image Size: `33.84 MB`

- Image ID: `sha256:f1d045e9f59c441ebee6e42c4cf66e61d6f300587f253be6c5bb6aa34da10bfa`
- Created: `2022-10-30T15:06:19.279655566Z`
- Arch: `linux`/`amd64`
- Command: `["python3"]`
- Environment:
  - `PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG=C.UTF-8`
  - `GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D`
  - `PYTHON_VERSION=3.10.8`
  - `PYTHON_PIP_VERSION=22.2.2`
  - `PYTHON_SETUPTOOLS_VERSION=63.2.0`
  - `PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/5eaac1050023df1f5c98b173b248c260023f2278/public/get-pip.py`
  - `PYTHON_GET_PIP_SHA256=5aefe6ade911d997af080b315ebcb7f882212d070465df544e1175ac2be519b4`
  - `DOCKER_IMAGE=devdemisto/google-api-python3:1.0.0.36882`
- Labels:
  - `org.opencontainers.image.authors:Demisto <containers@demisto.com>`
  - `org.opencontainers.image.revision:0c563c743992f334de1b3487913a35562d46dd81`
  - `org.opencontainers.image.version:1.0.0.36882`

2022-10-31 08:51 UTC, JudahSchwartz requested changes
as we discussed, lets not create another seemingly duplicate google-api image. Are there any of these not in use? Which are we replacing by adding this?

2022-10-31 09:55 UTC, sapirshuker commented
> as we discussed, lets not create another seemingly duplicate google-api image. Are there any of these not in use? Which are we replacing by adding this?

@JudahSchwartz I will open a dev-task about the dockers google-api-py3 and googleapi-python3 in order to merge it to one docker image. currently i am using this docker only for tests. I don't have intent to merge it until we understand which one we replace by add this.

2022-10-31 10:09 UTC, dc-builder commented
# Docker Image Ready - Dev

Docker automatic build at CircleCI has deployed your docker image: devdemisto/google-api-python3:1.0.0.36914
It is available now on docker hub at: https://hub.docker.com/r/devdemisto/google-api-python3/tags
Get started by pulling the image:
```
docker pull devdemisto/google-api-python3:1.0.0.36914
```

## Docker Metadata
- Image Size: `44.58 MB`

- Image ID: `sha256:7ab8d1d00baab04d22ff13d7aa22da295f84fba18106f9155ec611783aee16a6`
- Created: `2022-10-31T10:08:58.44863662Z`
- Arch: `linux`/`amd64`
- Command: `["python3"]`
- Environment:
  - `PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG=C.UTF-8`
  - `GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D`
  - `PYTHON_VERSION=3.10.8`
  - `PYTHON_PIP_VERSION=22.2.2`
  - `PYTHON_SETUPTOOLS_VERSION=63.2.0`
  - `PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/5eaac1050023df1f5c98b173b248c260023f2278/public/get-pip.py`
  - `PYTHON_GET_PIP_SHA256=5aefe6ade911d997af080b315ebcb7f882212d070465df544e1175ac2be519b4`
  - `DOCKER_IMAGE=devdemisto/google-api-python3:1.0.0.36914`
- Labels:
  - `org.opencontainers.image.authors:Demisto <containers@demisto.com>`
  - `org.opencontainers.image.revision:fd249406bb5de98a348d3bbdba66f2d267950dda`
  - `org.opencontainers.image.version:1.0.0.36914`

2023-01-02 14:03 UTC, closed without merging